add_newline = false

# Main format string
format = "$username@$hostname:$directory$git_branch$git_status$character"

[username]
format = "[$user]($style)"
style_user = "green"
style_root = "red"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "cyan"
ssh_only = false

[directory]
format = "[$path]($style)"
style = "141"
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false
home_symbol = "~"

[git_branch]
format = " [$branch]($style)"
style = "yellow"

[git_status]
disabled = false
format = "[$conflicted$deleted$modified$renamed$staged$untracked$ahead_behind]($style)"
style = "red"
staged = "+"
modified = "!"
deleted = "x"
renamed = "»"
untracked = "?"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""

[character]
success_symbol = " [»](bold green)"
error_symbol = " [»](bold red)"